// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240222155953_populateProducts")]
    partial class populateProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Projekt.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "SweatShirts"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ListPrice")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<double?>("Price100")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<double?>("Price50")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Description = "Nike Air Force 1 är en legendarisk basketsko som först introducerades 1982 och är känd för att vara den första basketskon som använder Nike Air-teknologin. Denna innovation erbjuder överlägsen dämpning och stöd, vilket har bidragit till skons rykte på basketplanen och dess långvariga popularitet utanför den.",
                            ListPrice = 900.0,
                            Price = 1000.0,
                            Price100 = 700.0,
                            Price50 = 800.0,
                            Title = "Air Force 1"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nike",
                            Description = "Nike Blazer Mid '77 fångar den gamla skolans charm av basket med dess vintagestil och klassiska design. Skon har en robust konstruktion med en överdel i läder och mocka, kompletterat med en retro Swoosh-logotyp för en autentisk look. Dess simpla men stiliga utseende har gjort den till en favorit både på och utanför basketplanen.",
                            ListPrice = 1000.0,
                            Price = 1100.0,
                            Price100 = 800.0,
                            Price50 = 900.0,
                            Title = "Blazer Mid '77"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Adidas",
                            Description = "Adidas Campus är en ikonisk sneaker som ursprungligen lanserades på 1980-talet. Den är känd för sin låga profil, enkla design och hållbarhet, vilket gjort den till en favorit både inom skatekulturen och som en vardagssko.",
                            ListPrice = 1149.0,
                            Price = 1249.0,
                            Price100 = 849.0,
                            Price50 = 1049.0,
                            Title = "Campus"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Adidas",
                            Description = "Adidas Stan Smith är en tidlös tennissko som först släpptes på 1970-talet. Med sin minimalistiska design och signaturdetaljer som de perforerade tre ränderna och porträttet av Stan Smith på tungan, har denna sko blivit en ikon inom modevärlden. Dess låga profil och enkla estetik gör den till en mångsidig sko som passar till nästan allt.",
                            ListPrice = 850.0,
                            Price = 950.0,
                            Price100 = 650.0,
                            Price50 = 750.0,
                            Title = "Stan Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
